server:
  port: 8089

spring:
  application:
    name: footballhub-admin-backend
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 100
      minimum-idle: 1
      idle-timeout: 300000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      schema: football
    url: jdbc:postgresql://localhost:5432/footballhub?currentSchema=football&charSet=UTF8
    username: footballhub
    password: footballhub
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

link:
  url:
    football-data-api: http://api.football-data.org/v4

football-data-api:
  x-auth-token: 453edd7035a845e9ba771641a9d56478